# -*- coding: utf-8 -*-
"""Projeto SCTEC_Lara Hassen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysZB1q3v2L5J6I8tHt0ZL7SUE5q5NEVT

# 1. Preparação do Ambiente de Análise
"""

# Instalação das dependências
!pip install kagglehub
!pip install pandas matplotlib

# Carregamento das bibliotecas
import os
import pandas as pd
import kagglehub
import matplotlib.pyplot as plt

"""# 2. Obtenção e Carregamento dos Dados"""

# Download da base de dados Sample Superstore
path = kagglehub.dataset_download("vivek468/superstore-dataset-final")

print("Path to dataset files:", path)

# Construção do caminho para o arquivo de dados
arquivo_csv = os.path.join(path, 'Sample - Superstore.csv')

# Importação dos dados para análise
df = pd.read_csv(arquivo_csv, encoding='latin-1', dtype={'Postal Code': str})

"""## Visualização inicial dos dados

Exibição das primeiras linhas do conjunto de dados para verificação da estrutura e conteúdo.
"""

# Verificação do carregamento da base de dados
df.head()

"""## Estatísticas descritivas

Resumo das principais medidas estatísticas das variáveis numéricas.
"""

# Identificação das colunas da base de dados
df.columns

# Visualização aleatória de 10 registros da base de dados
df.sample(10)

# Resumo da estrutura e dos tipos de dados da base
df.info()

# Estatísticas descritivas das variáveis numéricas
df.describe()

# Gráfico de Distribuição das Vendas
df['Sales'].plot(kind='hist', bins=50)
plt.title('Distribuição das Vendas')
plt.xlabel('Sales (USD)')
plt.show()

"""A distribuição das vendas apresenta concentração em valores baixos, com presença de poucos valores elevados."""

# Verificação da presença de valores nulos na base de dados
df.isnull().sum()

# Não foram identificados valores ausentes na base de dados.

# Verificação da existência de registros duplicados
df.duplicated().sum()

# A verificação não constatou a existencia de duplicatas que pudessem alterar o valor total.

"""# 3. Interpretação dos Resultados"""

# Conversão da coluna de data para o formato datetime
df['data pedido'] = pd.to_datetime(
    df['Order Date'],
    format='%m/%d/%Y',
    errors='coerce'
)

df['data pedido'].head()

"""A coluna de data de pedido foi convertida para o formato *datetime*, permitindo a realização de análises temporais como tendências de vendas ao longo do tempo, agrupamentos por mês ou ano e séries históricas.

"""

# Cálculo da média das vendas
df['Sales'].mean()

# Cálculo da mediana das vendas
df['Sales'].median()

# Cálculo do desvio da padrão das vendas
df['Sales'].std()

# Identificação da categoria de produto mais vendida
df['Category'].mode()

print(f'Média: {df["Sales"].mean()}')
print(f'Mediana: {df["Sales"].median()}')
print(f'Desvio padrão: {df["Sales"].std()}')
print(f'Categoria mais vendida: {df["Category"].mode()}')

"""A média das vendas (229,86 dólares) é significativamente maior que a mediana (54,49 dólares), indicando uma distribuição assimétrica com presença de valores elevados que puxam a média para cima. O desvio padrão (623,25 dólares) evidencia alta variabilidade nas vendas e possível presença de outliers. A categoria mais frequente na base é Office Supplies, indicando maior número de registros nessa categoria."""

# Análise da distribuição das vendas por percentis
percentis = df['Sales'].quantile([0.10, 0.25, 0.5, 0.75, 0.90, 0.99])
print(percentis)

"""A análise dos percentis das vendas evidencia uma forte concentração de valores em faixas mais baixas. Cerca de 50% das vendas são inferiores a 54,49 dólares, enquanto 75% não ultrapassam 209,94 dólares, indicando que a maioria das transações possui baixo valor. Por outro lado, o percentil 99 mostra a presença de vendas significativamente elevadas no valor de 2.481,69 dólares, sugerindo a existência de outliers e uma distribuição assimétrica à direita."""

# Cálculo dos quartis das vendas
df['Sales'].quantile([0.25, 0.50, 0.75])

"""Os quartis das vendas indicam que 25% das transações possuem valor de até 17,28 dólares, enquanto a mediana (50%) é de 54,49 dólares, representando o ponto central da distribuição. Já 75% das vendas não ultrapassam 209,94 dólares, evidenciando que a maior parte das transações ocorre em valores relativamente baixos. Esses resultados reforçam o resultado aprensato na Análise da distribuição das vendas por percentis, quanto a presença de uma distribuição assimétrica, com concentração de vendas em faixas menores e alguns valores mais elevados."""

# Distribuição dos registros por categoria de produto
df['Category'].value_counts()

"""A distribuição dos registros por categoria de produto mostra que **Office Supplies** concentra a maior parte das observações (**6026**), seguida por **Furniture** (**2121**) e **Technology** (**1847**). Isso indica que há maior volume de registros relacionados a Office Supplies, enquanto a categoria Technology apresenta o menor número de ocorrências. Essa análise evidencia a predominância de uma categoria em termos de frequência de registros.
* O que não necessariamente reflete volume de vendas ou lucratividade.
"""

df.groupby('Category')[['Sales','Profit']].sum()

categoria = df.groupby('Category')[['Sales','Profit']].sum()

categoria.plot(kind='bar')
plt.title('Vendas e Lucro por Categoria')
plt.ylabel('Valor (USD)')
plt.xticks(rotation=0)
plt.show()

"""A análise por categoria mostra que **Technology** lidera em vendas com valor total de 836.154,03 dólares e lucro de 145.454,95 dólares. **Furniture** tem alto volume de vendas com valor total de 741.999,80 dólares, mas o menor lucro é de 18.451,27 dólares, indicando baixa rentabilidade. Já **Office Supplies** apresenta vendas menores com valor total de 719.047,03 dólares, porém bom lucro no valor de 122.490,80 dólares, sugerindo melhor margem relativa."""

# Análise do desempenho de vendas e lucro por segmento de cliente
df.groupby('Segment')[['Sales','Profit']].sum()

segmento = df.groupby('Segment')[['Sales','Profit']].sum()

segmento.plot(kind='bar')
plt.title('Vendas e Lucro por Segmento de Cliente')
plt.ylabel('Valor (USD)')
plt.xticks(rotation=0)
plt.show()

"""A análise por segmento de cliente indica que o segmento **Consumer** concentra o maior volume de vendas 1.161.401,00 dólares e também o maior lucro 134.119,21 dólares, sendo o principal motor de receita da empresa. O segmento **Corporate** ocupa a segunda posição, com vendas de 706.146,40 dólares e lucro de 91.979,13 dólares. Já o segmento **Home Office** apresenta o menor desempenho, com 429.653,10 dólares em vendas e 60.298,68 dólares em lucro, indicando menor participação no resultado geral da empresa."""

# Análise do desempenho de vendas e lucro por região
df.groupby('Region')[['Sales','Profit']].sum()

regiao = df.groupby('Region')[['Sales','Profit']].sum()

regiao.plot(kind='bar')
plt.title('Vendas e Lucro por Região')
plt.ylabel('Valor (USD)')
plt.xticks(rotation=0)
plt.show()

"""A análise por região indica que **West** apresenta o maior volume de vendas com valor total de 725.457,82dólares e também o maior lucro no valor de 108.418,45 dólares, sendo a região de melhor desempenho. A região **East** aparece em segundo lugar, com 678.781,24 dólares em vendas e 91.522,78 dólares em lucro. A região **Central** possui vendas intermediárias com valor total de 501.239,89 dólares, porém o menor lucro, no valor de 39.706,36 dólares, indicando menor rentabilidade. Já a região **South** apresenta o menor volume de vendas com valor total de 391.721,91 dólares, e com lucro moderado de US$ 46.749,43."""

# Análise da correlação entre desconto e lucro
df[['Discount','Profit']].corr()

plt.scatter(df['Discount'], df['Profit'], alpha=0.3)
plt.title('Relação entre Desconto e Lucro')
plt.xlabel('Discount')
plt.ylabel('Profit')
plt.show()

"""A correlação entre desconto e lucro é negativa (-0,219*), indicando uma relação inversa fraca entre as variáveis. Isso sugere que, em geral, aumentos no desconto tendem a estar associados a reduções no lucro, embora essa relação não seja forte. Esse resultado indica que outros fatores também influenciam a rentabilidade, além do nível de desconto aplicado.

*O valor de correlação entre desconto e lucro não possui unidade de medida, sendo apenas um indicador estatístico que varia entre -1 e 1 e representa a força e a direção da relação entre as variáveis.
"""